# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/bin/CGAL-5.0.1/examples/Custom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/bin/CGAL-5.0.1/examples/Custom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/bin/CGAL-5.0.1/examples/Custom/CMakeFiles /usr/local/bin/CGAL-5.0.1/examples/Custom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/bin/CGAL-5.0.1/examples/Custom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sortingspatial

# Build rule for target.
sortingspatial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sortingspatial
.PHONY : sortingspatial

# fast build rule for target.
sortingspatial/fast:
	$(MAKE) -f CMakeFiles/sortingspatial.dir/build.make CMakeFiles/sortingspatial.dir/build
.PHONY : sortingspatial/fast

#=============================================================================
# Target rules for targets named ALL_CGAL_TARGETS

# Build rule for target.
ALL_CGAL_TARGETS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ALL_CGAL_TARGETS
.PHONY : ALL_CGAL_TARGETS

# fast build rule for target.
ALL_CGAL_TARGETS/fast:
	$(MAKE) -f CMakeFiles/ALL_CGAL_TARGETS.dir/build.make CMakeFiles/ALL_CGAL_TARGETS.dir/build
.PHONY : ALL_CGAL_TARGETS/fast

#=============================================================================
# Target rules for targets named array_convex_hull_2

# Build rule for target.
array_convex_hull_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 array_convex_hull_2
.PHONY : array_convex_hull_2

# fast build rule for target.
array_convex_hull_2/fast:
	$(MAKE) -f CMakeFiles/array_convex_hull_2.dir/build.make CMakeFiles/array_convex_hull_2.dir/build
.PHONY : array_convex_hull_2/fast

#=============================================================================
# Target rules for targets named cgal_check_build_system

# Build rule for target.
cgal_check_build_system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cgal_check_build_system
.PHONY : cgal_check_build_system

# fast build rule for target.
cgal_check_build_system/fast:
	$(MAKE) -f CMakeFiles/cgal_check_build_system.dir/build.make CMakeFiles/cgal_check_build_system.dir/build
.PHONY : cgal_check_build_system/fast

#=============================================================================
# Target rules for targets named convex_hull

# Build rule for target.
convex_hull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convex_hull
.PHONY : convex_hull

# fast build rule for target.
convex_hull/fast:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/build
.PHONY : convex_hull/fast

#=============================================================================
# Target rules for targets named convex_hull_naive

# Build rule for target.
convex_hull_naive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convex_hull_naive
.PHONY : convex_hull_naive

# fast build rule for target.
convex_hull_naive/fast:
	$(MAKE) -f CMakeFiles/convex_hull_naive.dir/build.make CMakeFiles/convex_hull_naive.dir/build
.PHONY : convex_hull_naive/fast

#=============================================================================
# Target rules for targets named sorting

# Build rule for target.
sorting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorting
.PHONY : sorting

# fast build rule for target.
sorting/fast:
	$(MAKE) -f CMakeFiles/sorting.dir/build.make CMakeFiles/sorting.dir/build
.PHONY : sorting/fast

array_convex_hull_2.o: array_convex_hull_2.cpp.o

.PHONY : array_convex_hull_2.o

# target to build an object file
array_convex_hull_2.cpp.o:
	$(MAKE) -f CMakeFiles/array_convex_hull_2.dir/build.make CMakeFiles/array_convex_hull_2.dir/array_convex_hull_2.cpp.o
.PHONY : array_convex_hull_2.cpp.o

array_convex_hull_2.i: array_convex_hull_2.cpp.i

.PHONY : array_convex_hull_2.i

# target to preprocess a source file
array_convex_hull_2.cpp.i:
	$(MAKE) -f CMakeFiles/array_convex_hull_2.dir/build.make CMakeFiles/array_convex_hull_2.dir/array_convex_hull_2.cpp.i
.PHONY : array_convex_hull_2.cpp.i

array_convex_hull_2.s: array_convex_hull_2.cpp.s

.PHONY : array_convex_hull_2.s

# target to generate assembly for a file
array_convex_hull_2.cpp.s:
	$(MAKE) -f CMakeFiles/array_convex_hull_2.dir/build.make CMakeFiles/array_convex_hull_2.dir/array_convex_hull_2.cpp.s
.PHONY : array_convex_hull_2.cpp.s

convex_hull.o: convex_hull.cpp.o

.PHONY : convex_hull.o

# target to build an object file
convex_hull.cpp.o:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.o
.PHONY : convex_hull.cpp.o

convex_hull.i: convex_hull.cpp.i

.PHONY : convex_hull.i

# target to preprocess a source file
convex_hull.cpp.i:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.i
.PHONY : convex_hull.cpp.i

convex_hull.s: convex_hull.cpp.s

.PHONY : convex_hull.s

# target to generate assembly for a file
convex_hull.cpp.s:
	$(MAKE) -f CMakeFiles/convex_hull.dir/build.make CMakeFiles/convex_hull.dir/convex_hull.cpp.s
.PHONY : convex_hull.cpp.s

convex_hull_naive.o: convex_hull_naive.cpp.o

.PHONY : convex_hull_naive.o

# target to build an object file
convex_hull_naive.cpp.o:
	$(MAKE) -f CMakeFiles/convex_hull_naive.dir/build.make CMakeFiles/convex_hull_naive.dir/convex_hull_naive.cpp.o
.PHONY : convex_hull_naive.cpp.o

convex_hull_naive.i: convex_hull_naive.cpp.i

.PHONY : convex_hull_naive.i

# target to preprocess a source file
convex_hull_naive.cpp.i:
	$(MAKE) -f CMakeFiles/convex_hull_naive.dir/build.make CMakeFiles/convex_hull_naive.dir/convex_hull_naive.cpp.i
.PHONY : convex_hull_naive.cpp.i

convex_hull_naive.s: convex_hull_naive.cpp.s

.PHONY : convex_hull_naive.s

# target to generate assembly for a file
convex_hull_naive.cpp.s:
	$(MAKE) -f CMakeFiles/convex_hull_naive.dir/build.make CMakeFiles/convex_hull_naive.dir/convex_hull_naive.cpp.s
.PHONY : convex_hull_naive.cpp.s

sorting.o: sorting.cpp.o

.PHONY : sorting.o

# target to build an object file
sorting.cpp.o:
	$(MAKE) -f CMakeFiles/sorting.dir/build.make CMakeFiles/sorting.dir/sorting.cpp.o
.PHONY : sorting.cpp.o

sorting.i: sorting.cpp.i

.PHONY : sorting.i

# target to preprocess a source file
sorting.cpp.i:
	$(MAKE) -f CMakeFiles/sorting.dir/build.make CMakeFiles/sorting.dir/sorting.cpp.i
.PHONY : sorting.cpp.i

sorting.s: sorting.cpp.s

.PHONY : sorting.s

# target to generate assembly for a file
sorting.cpp.s:
	$(MAKE) -f CMakeFiles/sorting.dir/build.make CMakeFiles/sorting.dir/sorting.cpp.s
.PHONY : sorting.cpp.s

sortingspatial.o: sortingspatial.cpp.o

.PHONY : sortingspatial.o

# target to build an object file
sortingspatial.cpp.o:
	$(MAKE) -f CMakeFiles/sortingspatial.dir/build.make CMakeFiles/sortingspatial.dir/sortingspatial.cpp.o
.PHONY : sortingspatial.cpp.o

sortingspatial.i: sortingspatial.cpp.i

.PHONY : sortingspatial.i

# target to preprocess a source file
sortingspatial.cpp.i:
	$(MAKE) -f CMakeFiles/sortingspatial.dir/build.make CMakeFiles/sortingspatial.dir/sortingspatial.cpp.i
.PHONY : sortingspatial.cpp.i

sortingspatial.s: sortingspatial.cpp.s

.PHONY : sortingspatial.s

# target to generate assembly for a file
sortingspatial.cpp.s:
	$(MAKE) -f CMakeFiles/sortingspatial.dir/build.make CMakeFiles/sortingspatial.dir/sortingspatial.cpp.s
.PHONY : sortingspatial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sortingspatial"
	@echo "... ALL_CGAL_TARGETS"
	@echo "... array_convex_hull_2"
	@echo "... cgal_check_build_system"
	@echo "... convex_hull"
	@echo "... convex_hull_naive"
	@echo "... sorting"
	@echo "... array_convex_hull_2.o"
	@echo "... array_convex_hull_2.i"
	@echo "... array_convex_hull_2.s"
	@echo "... convex_hull.o"
	@echo "... convex_hull.i"
	@echo "... convex_hull.s"
	@echo "... convex_hull_naive.o"
	@echo "... convex_hull_naive.i"
	@echo "... convex_hull_naive.s"
	@echo "... sorting.o"
	@echo "... sorting.i"
	@echo "... sorting.s"
	@echo "... sortingspatial.o"
	@echo "... sortingspatial.i"
	@echo "... sortingspatial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

